= WazamonoCore 同梱版について =

このライブラリは https://github.com/arduino-libraries/Ethernet[arduino-libraries/Ethernet] v2.0.2 を
WazamonoCore(AVR DU)向けに調整したものです。変更点は `src/utility/w5100.h` の2点のみで、API は公式版と同一です。

* SPI クロック要求を 14 MHz → 8 MHz に変更 (`ARDUINO_ARCH_MEGAAVR` のとき)。
  AVR DU の SPI 分周は /2, /4, /8 ... のため、24 MHz 動作では 14 MHz 要求が 12 MHz に丸められ、
  W5100 搭載シールドが応答しない(レジスタ読み値が1ビットずれる)ことを実機で確認済み。
  8 MHz 要求なら F_CPU = 12/16/20/24 MHz でそれぞれ 6/8/5/6 MHz となり、いずれも W5100 で動作する。
* チップセレクトの操作を PORT の OUTSET/OUTCLR レジスタによるアトミック書き込みに変更。

各ボードでの配線:

* Wazamono Tsurugi: Uno R3 用イーサネットシールドを直挿しで使用でき、CS = D10(W5100) / D4(SD カード) の標準配線がそのまま使えます。
  D13(SCK) は Serial2 の TX と共用のため、Ethernet/SD 使用中は Serial2 を開かないでください。
* Wazamono Tachi: MOSI = D16 / MISO = D14 / SCK = D15。CS は任意の GPIO(`Ethernet.init(pin)` で指定)。D15(SCK) は Serial2 の TX と共用です。
* Wazamono Kunai: MOSI = D10 / MISO = D9 / SCK = D8。CS は任意の GPIO(`Ethernet.init(pin)` で指定)。

:repository-owner: arduino-libraries
:repository-name: Ethernet

= {repository-name} Library for Arduino =

image:https://github.com/{repository-owner}/{repository-name}/actions/workflows/check-arduino.yml/badge.svg["Check Arduino status", link="https://github.com/{repository-owner}/{repository-name}/actions/workflows/check-arduino.yml"]
image:https://github.com/{repository-owner}/{repository-name}/actions/workflows/compile-examples.yml/badge.svg["Compile Examples status", link="https://github.com/{repository-owner}/{repository-name}/actions/workflows/compile-examples.yml"]
image:https://github.com/{repository-owner}/{repository-name}/actions/workflows/spell-check.yml/badge.svg["Spell Check status", link="https://github.com/{repository-owner}/{repository-name}/actions/workflows/spell-check.yml"]

With the Arduino Ethernet Shield, this library allows an Arduino board to connect to the internet.

For more information about this library please visit us at
https://www.arduino.cc/en/Reference/{repository-name}

== License ==

Copyright (c) 2010 Arduino LLC. All right reserved.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
